"""Factor configuration for Newhedge fetches."""
FACTORS = [
    {"name": "mvrv", "chart_slug": "mvrv", "metric_name": "mvrv", "notes": "MVRV ratio."},
    {"name": "mvrv_z_score", "chart_slug": "mvrv-z-score", "metric_name": "mvrv_z", "notes": "Standardized MVRV."},
    {"name": "nupl", "chart_slug": "net-unrealized-profit-loss", "metric_name": "net_unrealized_profit_loss", "notes": "Net Unrealized Profit/Loss."},
    {"name": "sopr", "chart_slug": "spent-output-profit-ratio", "metric_name": "sopr", "notes": "SOPR."},
    {"name": "realized_price", "chart_slug": "realized-price", "metric_name": "realized_price", "notes": "Aggregate cost basis."},
    {"name": "realized_marketcap", "chart_slug": "realized-marketcap", "metric_name": "realized_cap", "notes": "Realized cap."},
    {"name": "active_addresses", "chart_slug": "active-addresses", "metric_name": "active_addresses", "notes": "Daily active addresses."},
    {"name": "transaction_volume", "chart_slug": "transaction-volume", "metric_name": "sent_sum_usd", "notes": "Daily transaction volume in USD."},
    {"name": "addresses_nonzero_balance", "chart_slug": "addresses-with-non-zero-balance", "metric_name": "addresses_with_a_non_zero_balance", "notes": "Wallet count."},
    {"name": "coin_days_destroyed", "chart_slug": "coin-days-destroyed", "metric_name": "coin_days_destroyed", "notes": "CDD."},
    {"name": "lth_supply", "chart_slug": "long-term-holder-supply", "metric_name": "supply_lth", "notes": "LTH supply."},
    {"name": "supply_in_profit", "chart_slug": "total-supply-in-profit", "metric_name": "supply_in_profit", "notes": "% of supply above cost basis."},
    {"name": "network_difficulty", "chart_slug": "network-difficulty", "metric_name": "network_difficulty", "notes": "Mining difficulty."},
    {"name": "miner_revenue", "chart_slug": "miner-revenue", "metric_name": "miner_revenue", "notes": "Daily miner revenue in USD."},
    {"name": "hashprice", "chart_slug": "hashprice", "metric_name": "hashprice_btc", "notes": "Mining profitability."},
    {"name": "puell_multiple", "chart_slug": "puell-multiple", "metric_name": "puell_multiple", "notes": "Miner revenue stress."},
    {"name": "btc_dominance", "chart_slug": "bitcoin-dominance", "metric_name": "btc_dominance", "notes": "BTC market cap share."},
    {"name": "exchange_reserves", "chart_slug": "exchange-reserves", "metric_name": "exchange_reserves_btc", "notes": "BTC held on exchanges."},
    {"name": "futures_open_interest", "chart_slug": "total-futures-open-interest", "metric_name": "total_futures_open_interest", "notes": "Aggregate futures OI."},
    {"name": "funding_rate", "chart_slug": "funding-rate", "metric_name": "bitcoin_funding_rate_binance", "notes": "Binance funding rate proxy."},
    {"name": "etf_flows_usd", "chart_slug": "spot-bitcoin-etf-total-net-flows", "metric_name": "spot_btc_etf_total_flows_usd", "notes": "Aggregate ETF flows USD."},
    {"name": "treasury_10y", "chart_slug": "10-year-treasury-yield", "metric_name": "treasury_10y_price_usd", "notes": "10Y US Treasury yield."},
]